# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QVBoxLayout
from PyQt5.QtCore import pyqtSignal
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import front.import_browser as import_browser
import front.export_browser as export_browser
import front.oscillogramMpl as oscillogramMpl
import pandas as pd


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        super(Ui_MainWindow, self).__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 831)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(670, 555))
        MainWindow.setBaseSize(QtCore.QSize(800, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameUpper = QtWidgets.QFrame(self.centralwidget)
        MainWindow.setWindowIcon(QtGui.QIcon('icon.png'))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameUpper.sizePolicy().hasHeightForWidth())
        self.frameUpper.setSizePolicy(sizePolicy)
        self.frameUpper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUpper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUpper.setObjectName("frameUpper")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameUpper)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frameParameters = QtWidgets.QFrame(self.frameUpper)
        self.frameParameters.setMinimumSize(QtCore.QSize(200, 0))
        self.frameParameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParameters.setObjectName("frameParameters")
        self.gridLayout = QtWidgets.QGridLayout(self.frameParameters)
        self.gridLayout.setObjectName("gridLayout")
        self.frameParSampling = QtWidgets.QFrame(self.frameParameters)
        self.frameParSampling.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParSampling.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParSampling.setObjectName("frameParSampling")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameParSampling)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelSampling = QtWidgets.QLabel(self.frameParSampling)
        self.labelSampling.setMaximumSize(QtCore.QSize(200, 19))
        self.labelSampling.setObjectName("labelSampling")
        self.horizontalLayout_8.addWidget(self.labelSampling)
        self.spinBoxSampling = QtWidgets.QSpinBox(self.frameParSampling)
        self.spinBoxSampling.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBoxSampling.setMaximum(999999999)
        self.spinBoxSampling.setSingleStep(10)
        self.spinBoxSampling.setObjectName("spinBoxSampling")
        self.horizontalLayout_8.addWidget(self.spinBoxSampling)
        self.gridLayout.addWidget(self.frameParSampling, 1, 0, 1, 1)
        self.frameParSelectEnd = QtWidgets.QFrame(self.frameParameters)
        self.frameParSelectEnd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParSelectEnd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParSelectEnd.setObjectName("frameParSelectEnd")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frameParSelectEnd)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelSelEnd = QtWidgets.QLabel(self.frameParSelectEnd)
        self.labelSelEnd.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelSelEnd.setObjectName("labelSelEnd")
        self.horizontalLayout_9.addWidget(self.labelSelEnd)
        self.doubleSpinBoxSelEnd = QtWidgets.QDoubleSpinBox(self.frameParSelectEnd)
        self.doubleSpinBoxSelEnd.setMaximum(1e+155)
        self.doubleSpinBoxSelEnd.setObjectName("doubleSpinBoxSelEnd")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxSelEnd)
        self.gridLayout.addWidget(self.frameParSelectEnd, 4, 0, 1, 1)
        self.frameParFilename = QtWidgets.QFrame(self.frameParameters)
        self.frameParFilename.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParFilename.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParFilename.setObjectName("frameParFilename")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frameParFilename)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelFilename = QtWidgets.QLabel(self.frameParFilename)
        self.labelFilename.setMinimumSize(QtCore.QSize(200, 0))
        self.labelFilename.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelFilename.setObjectName("labelFilename")
        self.horizontalLayout_10.addWidget(self.labelFilename)
        self.textFilename = QtWidgets.QTextEdit(self.frameParFilename)
        self.textFilename.setEnabled(True)
        self.textFilename.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.textFilename.setFont(font)
        self.textFilename.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.textFilename.setAutoFillBackground(True)
        self.textFilename.setDocumentTitle("")
        self.textFilename.setReadOnly(True)
        self.textFilename.setObjectName("textFilename")
        self.horizontalLayout_10.addWidget(self.textFilename)
        self.gridLayout.addWidget(self.frameParFilename, 0, 0, 1, 1)
        self.frameParSampleNum = QtWidgets.QFrame(self.frameParameters)
        self.frameParSampleNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParSampleNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParSampleNum.setObjectName("frameParSampleNum")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frameParSampleNum)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelSampleNum = QtWidgets.QLabel(self.frameParSampleNum)
        self.labelSampleNum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelSampleNum.setObjectName("labelSampleNum")
        self.horizontalLayout_11.addWidget(self.labelSampleNum)
        self.spinBoxSampleNum = QtWidgets.QSpinBox(self.frameParSampleNum)
        self.spinBoxSampleNum.setMaximum(999999999)
        self.spinBoxSampleNum.setObjectName("spinBoxSampleNum")
        self.horizontalLayout_11.addWidget(self.spinBoxSampleNum)
        self.gridLayout.addWidget(self.frameParSampleNum, 2, 0, 1, 1)
        self.frameParSelectBeg = QtWidgets.QFrame(self.frameParameters)
        self.frameParSelectBeg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParSelectBeg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParSelectBeg.setObjectName("frameParSelectBeg")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frameParSelectBeg)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelSelBeg = QtWidgets.QLabel(self.frameParSelectBeg)
        self.labelSelBeg.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelSelBeg.setObjectName("labelSelBeg")
        self.horizontalLayout_12.addWidget(self.labelSelBeg)
        self.doubleSpinBoxSelBeg = QtWidgets.QDoubleSpinBox(self.frameParSelectBeg)
        self.doubleSpinBoxSelBeg.setMaximum(1e+120)
        self.doubleSpinBoxSelBeg.setObjectName("doubleSpinBoxSelBeg")
        self.horizontalLayout_12.addWidget(self.doubleSpinBoxSelBeg)
        self.gridLayout.addWidget(self.frameParSelectBeg, 3, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frameParameters)
        self.frameButtons = QtWidgets.QFrame(self.frameUpper)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameButtons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pButtnImport = QtWidgets.QPushButton(self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButtnImport.sizePolicy().hasHeightForWidth())
        self.pButtnImport.setSizePolicy(sizePolicy)
        self.pButtnImport.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pButtnImport.setObjectName("pButtnImport")
        self.verticalLayout_3.addWidget(self.pButtnImport)
        self.pButtnExport = QtWidgets.QPushButton(self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButtnExport.sizePolicy().hasHeightForWidth())
        self.pButtnExport.setSizePolicy(sizePolicy)
        self.pButtnExport.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pButtnExport.setObjectName("pButtnExport")
        self.verticalLayout_3.addWidget(self.pButtnExport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.pButtnICARun = QtWidgets.QPushButton(self.frameButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButtnICARun.sizePolicy().hasHeightForWidth())
        self.pButtnICARun.setSizePolicy(sizePolicy)
        self.pButtnICARun.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pButtnICARun.setObjectName("pButtnICARun")
        self.verticalLayout_3.addWidget(self.pButtnICARun)
        self.horizontalLayout_7.addWidget(self.frameButtons)
        self.verticalLayout_6.addWidget(self.frameUpper)
        self.frameOscillogram = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOscillogram.sizePolicy().hasHeightForWidth())
        self.frameOscillogram.setSizePolicy(sizePolicy)
        self.frameOscillogram.setMinimumSize(QtCore.QSize(300, 200))
        self.frameOscillogram.setSizeIncrement(QtCore.QSize(500, 200))
        self.frameOscillogram.setBaseSize(QtCore.QSize(500, 200))
        self.frameOscillogram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOscillogram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOscillogram.setObjectName("frameOscillogram")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameOscillogram)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.widgetOscillogram = QtWidgets.QWidget(self.frameOscillogram)
        self.widgetOscillogram.setBaseSize(QtCore.QSize(0, 0))
        self.widgetOscillogram.setObjectName("widgetOscillogram")

        self.verticalLayout_4.addWidget(self.widgetOscillogram)
        self.verticalLayout_6.addWidget(self.frameOscillogram)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.frameOscillogram.setFrameStyle(QFrame.NoFrame)
        self.frameUpper.setFrameStyle(QFrame.NoFrame)
        self.frameParFilename.setFrameStyle(QFrame.NoFrame)
        self.frameParSampling.setFrameStyle(QFrame.NoFrame)
        self.frameParSelectBeg.setFrameStyle(QFrame.NoFrame)
        self.frameParSelectEnd.setFrameStyle(QFrame.NoFrame)
        self.frameParSampleNum.setFrameStyle(QFrame.NoFrame)
        self.prepare_oscillogram()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICA - GUI"))
        self.labelSampling.setText(_translate("MainWindow", "Próbkowanie"))
        self.labelSelEnd.setText(_translate("MainWindow", "Koniec zaznaczenia"))
        self.labelFilename.setText(_translate("MainWindow", "Zaimportowano z pliku:"))
        self.textFilename.setPlaceholderText(_translate("MainWindow", "Nie wskazano pliku"))
        self.labelSampleNum.setText(_translate("MainWindow", "Liczba próbek"))
        self.labelSelBeg.setText(_translate("MainWindow", "Początek zaznaczenia"))
        self.pButtnImport.setText(_translate("MainWindow", "Import..."))
        self.pButtnExport.setText(_translate("MainWindow", "Eksport..."))
        self.pButtnICARun.setText(_translate("MainWindow", "Uruchom ICA"))

    def prepare_oscillogram(self):
        pass
        self.oscillogramPyPlot = oscillogramMpl.OscillogramMpl()
        self.toolbarPyPlot = NavigationToolbar(self.oscillogramPyPlot, self.widgetOscillogram)
        self.layoutInOscillogram = QVBoxLayout(self.widgetOscillogram)
        self.layoutInOscillogram.addWidget(self.toolbarPyPlot)
        self.layoutInOscillogram.addWidget(self.oscillogramPyPlot)


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    # DEKLARACJE SYGNAŁÓW
    #   Żądanie przysłania widgetu z oscylogramem:
    sigImportFileRequest = pyqtSignal(str)  # żądanie importu pliku - argumentem jest filename
    sigExportFileRequest = pyqtSignal(str)  # analogicznie jak wyżej

    sigIcaRunningRequest = pyqtSignal()  # żądanie uruchomienia algorytmu ICA

    sigProvideSelectedRangeRequest = pyqtSignal()  # żądanie dostarczenia wybranego przez użytkownika zakresu

    sigSamplingSet = pyqtSignal(int)
    sigSampleNumSet = pyqtSignal(int)
    sigSelBegSet = pyqtSignal(float)
    sigSelEndSet = pyqtSignal(float)

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.pButtnImport.clicked.connect(self.on_click_pButtnImport)
        self.ui.pButtnExport.clicked.connect(self.on_click_pButtnExport)
        self.ui.pButtnICARun.clicked.connect(self.on_click_pButtnICARun)

        self.ui.spinBoxSampling.valueChanged.connect(self.vchange_Sampling)
        self.ui.spinBoxSampleNum.valueChanged.connect(self.vchange_SampleNum)
        self.ui.doubleSpinBoxSelBeg.valueChanged.connect(self.vchange_SelBeg)
        self.ui.doubleSpinBoxSelEnd.valueChanged.connect(self.vchange_SelEnd)
        self.ui.oscillogramPyPlot.sel_range.connect(self.set_selected_range_from_plt)

    def on_click_pButtnImport(self):
        self.importBrowserWindow = import_browser.Ui_QDialogImportBrowser()
        self.importBrowserWindow.show()
        self.importBrowserWindow.filepath_signal.connect(self.handle_import_filepath)

    def handle_import_filepath(self, value):
        self.ui.textFilename.setPlainText(value)
        self.sigImportFileRequest.emit(value)
        print("Importing file:", value)

    def update_oscillogram_content(self, dataframe: pd.DataFrame):
        print(dataframe)
        self.ui.oscillogramPyPlot.updateOscillogram(dataframe)

    def on_click_pButtnExport(self):
        self.exportBrowserWindow = export_browser.Ui_QDialogExportBrowser()
        self.exportBrowserWindow.show()
        self.exportBrowserWindow.fileSaveRequested.connect(self.handle_export_request)

    def handle_export_request(self, value):
        self.sigExportFileRequest.emit(value)
        print("Need to save ", value)  # DZIAŁA
        # Tutaj wstawić metodę, która przekazuje wartość do pliku .csv

    def on_click_pButtnICARun(self):
        print("Zażądano uruchomienia algorytmu ICA")
        self.sigIcaRunningRequest.emit()

    def vchange_SelBeg(self, value):
        self.sigSelBegSet.emit(value)

    def vchange_SampleNum(self, value):
        self.sigSampleNumSet.emit(value)

    def vchange_SelEnd(self, value):
        self.sigSelEndSet.emit(value)

    def vchange_Sampling(self, value):
        self.sigSamplingSet.emit(value)

    def set_selected_range(self, beg, end):
        self.ui.doubleSpinBoxSelBeg = beg
        self.ui.doubleSpinBoxSelEnd = end
        print(beg, end)

    def set_selected_range_from_plt(self, beg, end):
        self.ui.doubleSpinBoxSelBeg.setValue(beg)
        self.ui.doubleSpinBoxSelEnd.setValue(end)
        self.vchange_SelBeg(beg)
        self.vchange_SelEnd(end)
