# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'front/import_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QDialog, QFileDialog

class Ui_QDialogImportBrowser(QDialog):

    filepath_signal = pyqtSignal(str)

    def __init__(self):
        self.filepath = ""
        super().__init__()
        self.setupUi(self)
    def setupUi(self, QDialogImportBrowser):
        QDialogImportBrowser.setObjectName("QDialogImportBrowser")
        QDialogImportBrowser.resize(525, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QDialogImportBrowser.sizePolicy().hasHeightForWidth())
        QDialogImportBrowser.setSizePolicy(sizePolicy)
        QDialogImportBrowser.setMinimumSize(QtCore.QSize(525, 150))
        QDialogImportBrowser.setMaximumSize(QtCore.QSize(525, 150))
        QDialogImportBrowser.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(QDialogImportBrowser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameFilepath = QtWidgets.QFrame(QDialogImportBrowser)
        self.frameFilepath.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frameFilepath.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFilepath.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFilepath.setObjectName("frameFilepath")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameFilepath)
        self.verticalLayout.setObjectName("verticalLayout")
        self.providedFilepath = QtWidgets.QPlainTextEdit(self.frameFilepath)
        self.providedFilepath.setMaximumSize(QtCore.QSize(10000, 30))
        self.providedFilepath.setObjectName("providedFilepath")
        self.verticalLayout.addWidget(self.providedFilepath)
        self.frameButtons = QtWidgets.QFrame(self.frameFilepath)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pButtnCancel = QtWidgets.QPushButton(self.frameButtons)
        self.pButtnCancel.setObjectName("pButtnCancel")
        self.horizontalLayout.addWidget(self.pButtnCancel)
        self.pButtnOk = QtWidgets.QPushButton(self.frameButtons)
        self.pButtnOk.setObjectName("pButtnOk")
        self.horizontalLayout.addWidget(self.pButtnOk)
        self.pButtnBrowse = QtWidgets.QPushButton(self.frameButtons)
        self.pButtnBrowse.setMinimumSize(QtCore.QSize(100, 0))
        self.pButtnBrowse.setObjectName("pButtnBrowse")
        self.horizontalLayout.addWidget(self.pButtnBrowse)
        self.verticalLayout.addWidget(self.frameButtons)
        self.verticalLayout_2.addWidget(self.frameFilepath)

        self.retranslateUi(QDialogImportBrowser)
        QtCore.QMetaObject.connectSlotsByName(QDialogImportBrowser)

    def retranslateUi(self, QDialogImportBrowser):
        _translate = QtCore.QCoreApplication.translate
        QDialogImportBrowser.setWindowTitle(_translate("QDialogImportBrowser", "Import z pliku .csv"))
        self.providedFilepath.setPlaceholderText(_translate("QDialogImportBrowser", "Ścieżka importowanego pliku..."))
        self.pButtnCancel.setText(_translate("QDialogImportBrowser", "Anuluj"))
        self.pButtnOk.setText(_translate("QDialogImportBrowser", "OK"))
        self.pButtnBrowse.setText(_translate("QDialogImportBrowser", "Przeglądaj..."))

        self.pButtnBrowse.clicked.connect(self.on_click_pButtnBrowse)
        self.pButtnOk.clicked.connect(self.on_click_pButtnOk)
        self.pButtnCancel.clicked.connect(self.on_click_pButtnCancel)


    def on_click_pButtnBrowse(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(self, "", "Comma Separated Values Files (*.csv)", options=options)
        if fileName:
            self.filepath = fileName
            self.providedFilepath.clear()
            self.providedFilepath.setPlainText(fileName)


    def on_click_pButtnOk(self):
        self.filepath_signal.emit(self.filepath)
        self.close()

    def on_click_pButtnCancel(self):
        self.close()
